name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Upload Release Assets
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build and publish the application
      - name: Build and publish
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o publish

      # Step 5: Archive the build output
      - name: Archive files
        uses: actions/upload-artifact@v3
        with:
          name: BMSOverlay
          path: publish/**

      # Step 6: Upload release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: publish/BMSOverlay.exe
          asset_name: BMSOverlay.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
